version: '3.8'

services:
  web-app:
    build:
      context: ./src/web
      dockerfile: infrastructure/docker/web-app.dockerfile
    ports:
      - "8080:80"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - VUE_APP_API_URL=http://api-gateway:5000
      - VUE_APP_ENABLE_LOGS=true
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_DEBUG=true
      - VUE_APP_DETAILED_ERRORS=true
    volumes:
      - ./src/web:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - frontend
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build:
      context: ./src/backend
      dockerfile: infrastructure/docker/api-gateway.dockerfile
    ports:
      - "5000:80"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION=redis:6379
      - SQL_CONNECTION=Server=localhost;Database=ServiceProvider;Trusted_Connection=True;MultipleActiveResultSets=true
      - ENABLE_SWAGGER=true
      - DETAILED_ERRORS=true
      - ASPNETCORE_URLS=http://+:80;http://+:5001
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=false
    volumes:
      - ./src/backend:/app
      - /app/obj
      - /app/bin
    depends_on:
      - redis
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    restart: unless-stopped
    command: redis-server --appendonly yes --loglevel verbose
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  redis-data:
    driver: local