apiVersion: v1
kind: Secret
metadata:
  name: service-provider-secrets
  namespace: default
  labels:
    app: service-provider
    environment: production
    managed-by: kubernetes
    encryption: aes256
    rotation-schedule: quarterly
  annotations:
    encryption.kubernetes.io/mode: aes-256
    rotation.kubernetes.io/schedule: "0 0 1 */3 *"  # Quarterly rotation
    audit.kubernetes.io/retention: "365d"
    security.kubernetes.io/compliance: "data-residency=region-specific"
type: Opaque
data:
  # Database Connection Strings
  ConnectionStrings__DefaultConnection: >-
    U2VydmVyPXNlcnZpY2UtcHJvdmlkZXItc3FsLmRhdGFiYXNlLndpbmRvd3MubmV0O0RhdGFiYXNlPVNlcnZpY2VQcm92aWRlckRCO1VzZXIgSUQ9YWRtaW47UGFzc3dvcmQ9eW91ci1zdHJvbmctcGFzc3dvcmQ7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU7RW5jcnlwdD10cnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZQ==
  ConnectionStrings__Redis: >-
    c2VydmljZS1wcm92aWRlci1yZWRpcy5yZWRpcy5jYWNoZS53aW5kb3dzLm5ldDo2MzgwLHBhc3N3b3JkPXlvdXItc3Ryb25nLXJlZGlzLXBhc3N3b3JkLHNzbD10cnVlLGFib3J0Q29ubmVjdD1mYWxzZQ==

  # Azure AD B2C Authentication
  AzureAdB2C__ClientSecret: >-
    YjJjLWNsaWVudC1zZWNyZXQteW91ci1zdHJvbmctc2VjcmV0LXZhbHVl

  # OneDrive Integration
  OneDrive__ClientSecret: >-
    b25lZHJpdmUtY2xpZW50LXNlY3JldC15b3VyLXN0cm9uZy1zZWNyZXQtdmFsdWU=

  # Application Insights
  ApplicationInsights__InstrumentationKey: >-
    YXBwbGljYXRpb24taW5zaWdodHMta2V5LXlvdXItc3Ryb25nLWtleS12YWx1ZQ==

  # JWT Authentication
  JwtBearer__SigningKey: >-
    and0LXNpZ25pbmcta2V5LTMyLWJ5dGVzLXN0cm9uZy1zZWNyZXQ=

  # Email Service
  Email__ApiKey: >-
    ZW1haWwtc2VydmljZS1hcGkta2V5LXlvdXItc3Ryb25nLWtleS12YWx1ZQ==

  # Azure Storage
  Storage__AccountKey: >-
    c3RvcmFnZS1hY2NvdW50LWtleS15b3VyLXN0cm9uZy1rZXktdmFsdWU=